//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokedex_Pokémon.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://img.rankedboost.com/wp-content/plugins/pokemon_go_tier_list_usermang/asse" +
            "ts/roles/Bug.png")]
        public string bug {
            get {
                return ((string)(this["bug"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://vignette.wikia.nocookie.net/pokemongo/images/0/0e/Dark.png/revision/lates" +
            "t/scale-to-width-down/340?cb=20161013132800")]
        public string dark {
            get {
                return ((string)(this["dark"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://vignette.wikia.nocookie.net/pokemongo/images/c/c7/Dragon.png/revision/lat" +
            "est/scale-to-width-down/340?cb=20161013132807")]
        public string dragon {
            get {
                return ((string)(this["dragon"]));
            }
            set {
                this["dragon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://vignette.wikia.nocookie.net/pokemongo/images/2/2f/Electric.png/revision/l" +
            "atest/top-crop/width/220/height/220?cb=20161013132813")]
        public string eletric {
            get {
                return ((string)(this["eletric"]));
            }
            set {
                this["eletric"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://vignette.wikia.nocookie.net/pokemongo/images/4/43/Fairy.png/revision/late" +
            "st/scale-to-width-down/340?cb=20161013132820")]
        public string fairy {
            get {
                return ((string)(this["fairy"]));
            }
            set {
                this["fairy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://vignette.wikia.nocookie.net/pokemongo/images/3/30/Fighting.png/revision/l" +
            "atest/top-crop/width/300/height/300?cb=20161013132827")]
        public string fighting {
            get {
                return ((string)(this["fighting"]));
            }
            set {
                this["fighting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://vignette.wikia.nocookie.net/pokemongo/images/3/30/Fire.png/revision/lates" +
            "t/scale-to-width-down/340?cb=20161013132833")]
        public string fire {
            get {
                return ((string)(this["fire"]));
            }
            set {
                this["fire"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://img.rankedboost.com/wp-content/uploads/2019/11/Flying-Type-Pokemon-Sword-" +
            "and-Shield.png")]
        public string flying {
            get {
                return ((string)(this["flying"]));
            }
            set {
                this["flying"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://img.rankedboost.com/wp-content/plugins/pokemon_go_tier_list_usermang/asse" +
            "ts/roles/Ghost.png")]
        public string ghost {
            get {
                return ((string)(this["ghost"]));
            }
            set {
                this["ghost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://vignette.wikia.nocookie.net/pokemongo/images/c/c5/Grass.png/revision/late" +
            "st/top-crop/width/220/height/220?cb=20161013132855")]
        public string grass {
            get {
                return ((string)(this["grass"]));
            }
            set {
                this["grass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://vignette.wikia.nocookie.net/pokemongo/images/0/0b/Rock.png/revision/lates" +
            "t/top-crop/width/300/height/300?cb=20161013133022")]
        public string ground {
            get {
                return ((string)(this["ground"]));
            }
            set {
                this["ground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cdn.icon-icons.com/icons2/2035/PNG/512/weather_snow_ice_icon_124163.png")]
        public string ice {
            get {
                return ((string)(this["ice"]));
            }
            set {
                this["ice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://vignette.wikia.nocookie.net/pokemongo/images/f/fb/Normal.png/revision/lat" +
            "est/scale-to-width-down/64?cb=20161013132914")]
        public string normal {
            get {
                return ((string)(this["normal"]));
            }
            set {
                this["normal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://vignette.wikia.nocookie.net/pokemongo/images/0/05/Poison.png/revision/lat" +
            "est/top-crop/width/220/height/220?cb=20161013133014")]
        public string poison {
            get {
                return ((string)(this["poison"]));
            }
            set {
                this["poison"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://img.rankedboost.com/wp-content/plugins/pokemon_go_tier_list_usermang/asse" +
            "ts/roles/Psychic.png")]
        public string psychic {
            get {
                return ((string)(this["psychic"]));
            }
            set {
                this["psychic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://vignette.wikia.nocookie.net/pokemongo/images/0/0b/Rock.png/revision/lates" +
            "t/top-crop/width/300/height/300?cb=20161013133022")]
        public string rock {
            get {
                return ((string)(this["rock"]));
            }
            set {
                this["rock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://img.rankedboost.com/wp-content/plugins/pokemon_go_tier_list_usermang/asse" +
            "ts/roles/Steel.png")]
        public string steel {
            get {
                return ((string)(this["steel"]));
            }
            set {
                this["steel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://vignette.wikia.nocookie.net/pokemongo/images/9/9d/Water.png/revision/late" +
            "st?cb=20161013133222")]
        public string water {
            get {
                return ((string)(this["water"]));
            }
            set {
                this["water"] = value;
            }
        }
    }
}
